apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ryanj6-poi-map-app-dev
  annotations:
    argocd/app-name: ryanj6-poi-map-app-dev
    backstage.io/kubernetes-id: ryanj6-poi-map-app-dev
    backstage.io/kubernetes-namespace: ryanj6
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=ryanj6-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23JanusN/ryanj6-frontend
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23bis.17gd.p1.openshiftapps.com/dev-pipelines/ns/ryanj6/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23bis.17gd.p1.openshiftapps.com/k8s/ns/ryanj6/deployments/poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23bis.17gd.p1.openshiftapps.com/#https://github.com/Summit23JanusN/ryanj6-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://poi-map-app-ryanj6.apps.summit23bis.17gd.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:ryanj"
  system: workshop-system-ryanj6
  consumesApis:
    - gateway-api-ryanj6
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ryanj6
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:ryanj"
